### ISSUE TITLE
Ability to run all railway commands with RAILWAY_TOKEN

### ISSUE THREAD

**Issue by elkevinwolf** [railwayapp/cli#105]
> First of all, I want to thank all the contributors who made Railway possible, I am exploring using it for my next project (a [Remix](https://remix.run) app with a Postgres database consumed by [Prisma](https://prisma.io)) because I have searched for existing services that allows me to automatically create per-environment databases and so far Railway has been the only one that allowed me to to this -- great work!

## The Problem

I want to create a GitHub Action for my project that first validates the project (build, lint, test) and then, only if those tests passes, deploy to Railway. This is because, currently, only the `railway run` command is reading the `RAILWAY_TOKEN` environment variable.

## Proposed solution

If all commands could read the `RAILWAY_TOKEN` environment variable, it would unleash its power by making it completely usable in headless environments like CI/CD systems.

**Comment by berviantoleo** [comment]
I looking forward in this too. I really need for `railway up`. Maybe I can help about this?

**Comment by JakeCooper** [comment]
Oh we didn't see this until now! I've added push events into our Discord for all future issues sorry about that!

Ya this would be great. We can have a look into it and circle back pretty soon! Will comment back when resolved

**Comment by AndreiJirohHaliliDev2006** [comment]
Hey, @elkevinwolf! The CLI now supports `RAILWAY_TOKEN` for all commands, as of [Railway Changelog #30](https://railway.app/changelog/2021-05-21#headless-ci/cd).

Also @JakeCooper, can you close and lock this issue as resolved? Thanks.

**Comment by JakeCooper** [comment]
Thanks @AndreiJirohHaliliDev2006!

Yes indeed!

**Comment by berviantoleo** [comment]
> 
> 
> Hey, @elkevinwolf! The CLI now supports `RAILWAY_TOKEN` for all commands, as of [Railway Changelog #30](https://railway.app/changelog/2021-05-21#headless-ci/cd).
> 
> Also @JakeCooper, can you close and lock this issue as resolved? Thanks.

Hi @AndreiJirohHaliliDev2006 / @JakeCooper , sorry I just want to make sure. Is it already published? I just curious, so for RAILWAY_TOKEN need to exactly one line with the command? or I can define from another line? Since I try at my github action, seems not work.

https://github.com/bervProject/tell-me-everything-api/runs/2671890622?check_suite_focus=true

![image](https://user-images.githubusercontent.com/15927349/119606420-c5185500-be1c-11eb-820d-c1477cd8f925.png)

**Comment by JakeCooper** [comment]
Oops! Just pushed a new release. Should be live as of 0.2.22!

**Comment by berviantoleo** [comment]
Seems I am not understand how to use `RAILWAY_TOKEN`. I still meet same error (ask me to login) at `0.2.22`. Maybe I need to login first with the `RAILWAY_TOKEN`?

https://github.com/bervProject/tell-me-everything-api/runs/2672088984?check_suite_focus=true

![image](https://user-images.githubusercontent.com/15927349/119793048-72b06480-bf00-11eb-97af-c60ea003f7e0.png)

**Comment by AndreiJirohHaliliDev2006** [comment]
> Seems I am not understand how to use `RAILWAY_TOKEN`. I still meet same error (ask me to login) at `0.2.22`. Maybe I need to login first with the `RAILWAY_TOKEN`?
> 
> https://github.com/bervProject/tell-me-everything-api/runs/2672088984?check_suite_focus=true
> 
> ![image](https://user-images.githubusercontent.com/15927349/119793048-72b06480-bf00-11eb-97af-c60ea003f7e0.png)

@berviantoleo You may need to do this instead:

```yml
# if you want to use environments in GitHub Actions to control deployments
# please see the GitHub Docs for that.
- name: Deploy to Railway
  run: |
     RAILWAY_TOKEN=$RAILWAY_TOKEN railway up
  env:
     RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
```

Also, it's currently not possible to sign in without email prompts (aka using an API token for logging in) to the CLI for now.

**Comment by gschier** [comment]
@berviantoleo it seems like it's being set to `""` by this line? 
<img width="237" alt="image" src="https://user-images.githubusercontent.com/587576/119854889-4d066980-bec6-11eb-9c6f-4f98e203d736.png">

**Comment by coffee-cup** [comment]
We've discovered an issue with using `railway up` and the project token. Will fix that today and let you know!

**Comment by berviantoleo** [comment]
> 
> 
> @berviantoleo it seems like it's being set to `""` by this line?
> <img alt="image" width="237" src="https://user-images.githubusercontent.com/587576/119854889-4d066980-bec6-11eb-9c6f-4f98e203d736.png">

Hi @gschier. No, it's not. It will be replaced when the value at the left side True. When the left side is false, the right side will not executed.



> 
> 
> We've discovered an issue with using `railway up` and the project token. Will fix that today and let you know!

I think this one the problem that I met. So I will wait the #126 instead.

**Comment by coffee-cup** [comment]
This should be fixed and live in release v0.2.25 https://github.com/railwayapp/cli/releases/tag/v0.2.25

You don't need to railway link or login at all. If you up with the RAILWAY_TOKEN the associated project and environment will be used.

Please let me know if you have any further issues with it

**Comment by berviantoleo** [comment]
> 
> 
> This should be fixed and live in release v0.2.25 https://github.com/railwayapp/cli/releases/tag/v0.2.25
> 
> You don't need to railway link or login at all. If you up with the RAILWAY_TOKEN the associated project and environment will be used.
> 
> Please let me know if you have any further issues with it

Thanks. It's working as expected.

**Comment by pascal-giguere** [comment]
This is still an issue in 2024.

- Works: `RAILWAY_TOKEN=$RAILWAY_TOKEN railway up`
- Doesn't work: `RAILWAY_TOKEN=$RAILWAY_TOKEN railway redeploy`

At a minimum, I'd suggest fixing the [misleading documentation](https://docs.railway.app/guides/cli#project-tokens):

<img width="670" alt="image" src="https://github.com/railwayapp/cli/assets/39274013/a81e7814-ff75-46fc-85e6-910cab9d68c4">

This suggests all commands support the `RAILWAY_TOKEN`, which is not the case. Maybe the documentation could explicitly mention which commands do/don't support it?

Fixing the doc is not as good as actually fixing the functionality, but at least it will prevent people from wasting time trying to follow the docs like we apparently have been for a few years now.
